/**
 * generated by Xtext 2.19.0
 */
package esir.comp.cpp.ui.contentassist;

import esir.comp.cpp.ui.contentassist.AbstractWhileDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class WhileDslProposalProvider extends AbstractWhileDslProposalProvider {
}
