/*
 * generated by Xtext 2.19.0
 */
package esir.comp.cpp.parser.antlr;

import com.google.inject.Inject;
import esir.comp.cpp.parser.antlr.internal.InternalWhileDslParser;
import esir.comp.cpp.services.WhileDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class WhileDslParser extends AbstractAntlrParser {

	@Inject
	private WhileDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalWhileDslParser createParser(XtextTokenStream stream) {
		return new InternalWhileDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public WhileDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(WhileDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
