/**
 * generated by Xtext 2.19.0
 */
package esir.comp.cpp.whileDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Command</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see esir.comp.cpp.whileDsl.WhileDslPackage#getCommand()
 * @model
 * @generated
 */
public interface Command extends EObject
{
} // Command
