/**
 * generated by Xtext 2.19.0
 */
package esir.comp.cpp.whileDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr And</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link esir.comp.cpp.whileDsl.ExprAnd#getExpressionsOr <em>Expressions Or</em>}</li>
 * </ul>
 *
 * @see esir.comp.cpp.whileDsl.WhileDslPackage#getExprAnd()
 * @model
 * @generated
 */
public interface ExprAnd extends EObject
{
  /**
   * Returns the value of the '<em><b>Expressions Or</b></em>' containment reference list.
   * The list contents are of type {@link esir.comp.cpp.whileDsl.ExprOr}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expressions Or</em>' containment reference list.
   * @see esir.comp.cpp.whileDsl.WhileDslPackage#getExprAnd_ExpressionsOr()
   * @model containment="true"
   * @generated
   */
  EList<ExprOr> getExpressionsOr();

} // ExprAnd
