/**
 * generated by Xtext 2.19.0
 */
package esir.comp.cpp.whileDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr Eq</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link esir.comp.cpp.whileDsl.ExprEq#getExprL <em>Expr L</em>}</li>
 *   <li>{@link esir.comp.cpp.whileDsl.ExprEq#getExprRSimple <em>Expr RSimple</em>}</li>
 *   <li>{@link esir.comp.cpp.whileDsl.ExprEq#getExprRExpr <em>Expr RExpr</em>}</li>
 * </ul>
 *
 * @see esir.comp.cpp.whileDsl.WhileDslPackage#getExprEq()
 * @model
 * @generated
 */
public interface ExprEq extends EObject
{
  /**
   * Returns the value of the '<em><b>Expr L</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr L</em>' containment reference.
   * @see #setExprL(ExprSimple)
   * @see esir.comp.cpp.whileDsl.WhileDslPackage#getExprEq_ExprL()
   * @model containment="true"
   * @generated
   */
  ExprSimple getExprL();

  /**
   * Sets the value of the '{@link esir.comp.cpp.whileDsl.ExprEq#getExprL <em>Expr L</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr L</em>' containment reference.
   * @see #getExprL()
   * @generated
   */
  void setExprL(ExprSimple value);

  /**
   * Returns the value of the '<em><b>Expr RSimple</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr RSimple</em>' containment reference.
   * @see #setExprRSimple(ExprSimple)
   * @see esir.comp.cpp.whileDsl.WhileDslPackage#getExprEq_ExprRSimple()
   * @model containment="true"
   * @generated
   */
  ExprSimple getExprRSimple();

  /**
   * Sets the value of the '{@link esir.comp.cpp.whileDsl.ExprEq#getExprRSimple <em>Expr RSimple</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr RSimple</em>' containment reference.
   * @see #getExprRSimple()
   * @generated
   */
  void setExprRSimple(ExprSimple value);

  /**
   * Returns the value of the '<em><b>Expr RExpr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr RExpr</em>' containment reference.
   * @see #setExprRExpr(Expr)
   * @see esir.comp.cpp.whileDsl.WhileDslPackage#getExprEq_ExprRExpr()
   * @model containment="true"
   * @generated
   */
  Expr getExprRExpr();

  /**
   * Sets the value of the '{@link esir.comp.cpp.whileDsl.ExprEq#getExprRExpr <em>Expr RExpr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr RExpr</em>' containment reference.
   * @see #getExprRExpr()
   * @generated
   */
  void setExprRExpr(Expr value);

} // ExprEq
