/**
 * generated by Xtext 2.19.0
 */
package esir.comp.cpp.whileDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Foreach Command</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link esir.comp.cpp.whileDsl.ForeachCommand#getExpElement <em>Exp Element</em>}</li>
 *   <li>{@link esir.comp.cpp.whileDsl.ForeachCommand#getExpList <em>Exp List</em>}</li>
 *   <li>{@link esir.comp.cpp.whileDsl.ForeachCommand#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see esir.comp.cpp.whileDsl.WhileDslPackage#getForeachCommand()
 * @model
 * @generated
 */
public interface ForeachCommand extends Command
{
  /**
   * Returns the value of the '<em><b>Exp Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp Element</em>' attribute.
   * @see #setExpElement(String)
   * @see esir.comp.cpp.whileDsl.WhileDslPackage#getForeachCommand_ExpElement()
   * @model
   * @generated
   */
  String getExpElement();

  /**
   * Sets the value of the '{@link esir.comp.cpp.whileDsl.ForeachCommand#getExpElement <em>Exp Element</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp Element</em>' attribute.
   * @see #getExpElement()
   * @generated
   */
  void setExpElement(String value);

  /**
   * Returns the value of the '<em><b>Exp List</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp List</em>' attribute.
   * @see #setExpList(String)
   * @see esir.comp.cpp.whileDsl.WhileDslPackage#getForeachCommand_ExpList()
   * @model
   * @generated
   */
  String getExpList();

  /**
   * Sets the value of the '{@link esir.comp.cpp.whileDsl.ForeachCommand#getExpList <em>Exp List</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp List</em>' attribute.
   * @see #getExpList()
   * @generated
   */
  void setExpList(String value);

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(Commands)
   * @see esir.comp.cpp.whileDsl.WhileDslPackage#getForeachCommand_Body()
   * @model containment="true"
   * @generated
   */
  Commands getBody();

  /**
   * Sets the value of the '{@link esir.comp.cpp.whileDsl.ForeachCommand#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(Commands value);

} // ForeachCommand
