/**
 * generated by Xtext 2.19.0
 */
package esir.comp.cpp.whileDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Nop Command</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see esir.comp.cpp.whileDsl.WhileDslPackage#getNopCommand()
 * @model
 * @generated
 */
public interface NopCommand extends Command
{
} // NopCommand
