/**
 * generated by Xtext 2.19.0
 */
package esir.comp.cpp.whileDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>While Command</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link esir.comp.cpp.whileDsl.WhileCommand#getCond <em>Cond</em>}</li>
 *   <li>{@link esir.comp.cpp.whileDsl.WhileCommand#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see esir.comp.cpp.whileDsl.WhileDslPackage#getWhileCommand()
 * @model
 * @generated
 */
public interface WhileCommand extends Command
{
  /**
   * Returns the value of the '<em><b>Cond</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cond</em>' attribute.
   * @see #setCond(String)
   * @see esir.comp.cpp.whileDsl.WhileDslPackage#getWhileCommand_Cond()
   * @model
   * @generated
   */
  String getCond();

  /**
   * Sets the value of the '{@link esir.comp.cpp.whileDsl.WhileCommand#getCond <em>Cond</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cond</em>' attribute.
   * @see #getCond()
   * @generated
   */
  void setCond(String value);

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(Commands)
   * @see esir.comp.cpp.whileDsl.WhileDslPackage#getWhileCommand_Body()
   * @model containment="true"
   * @generated
   */
  Commands getBody();

  /**
   * Sets the value of the '{@link esir.comp.cpp.whileDsl.WhileCommand#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(Commands value);

} // WhileCommand
