/*
 * generated by Xtext 2.19.0
 */
package esir.comp.cpp.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractWhileDslScopeProvider extends DelegatingScopeProvider {
}
