/**
 * generated by Xtext 2.19.0
 */
package esir.comp.cpp;

import esir.comp.cpp.WhileDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class WhileDslStandaloneSetup extends WhileDslStandaloneSetupGenerated {
  public static void doSetup() {
    new WhileDslStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
