/**
 * generated by Xtext 2.19.0
 */
package esir.comp.cpp.ui;

import esir.comp.cpp.ui.AbstractWhileDslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class WhileDslUiModule extends AbstractWhileDslUiModule {
  public WhileDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
