/**
 * generated by Xtext 2.19.0
 */
package esir.comp.cpp.ide;

import esir.comp.cpp.ide.AbstractWhileDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class WhileDslIdeModule extends AbstractWhileDslIdeModule {
}
