/**
 * generated by Xtext 2.19.0
 */
package esir.comp.cpp.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import esir.comp.cpp.WhileDslRuntimeModule;
import esir.comp.cpp.WhileDslStandaloneSetup;
import esir.comp.cpp.ide.WhileDslIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class WhileDslIdeSetup extends WhileDslStandaloneSetup {
  @Override
  public Injector createInjector() {
    WhileDslRuntimeModule _whileDslRuntimeModule = new WhileDslRuntimeModule();
    WhileDslIdeModule _whileDslIdeModule = new WhileDslIdeModule();
    return Guice.createInjector(Modules2.mixin(_whileDslRuntimeModule, _whileDslIdeModule));
  }
}
