/**
 * generated by Xtext 2.19.0
 */
package esir.comp.cpp.whileDsl.impl;

import esir.comp.cpp.whileDsl.Expr;
import esir.comp.cpp.whileDsl.ExprEq;
import esir.comp.cpp.whileDsl.ExprSimple;
import esir.comp.cpp.whileDsl.WhileDslPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Expr Eq</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link esir.comp.cpp.whileDsl.impl.ExprEqImpl#getExprLSimple <em>Expr LSimple</em>}</li>
 *   <li>{@link esir.comp.cpp.whileDsl.impl.ExprEqImpl#getExprRSimple <em>Expr RSimple</em>}</li>
 *   <li>{@link esir.comp.cpp.whileDsl.impl.ExprEqImpl#getExpr <em>Expr</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ExprEqImpl extends MinimalEObjectImpl.Container implements ExprEq
{
  /**
   * The cached value of the '{@link #getExprLSimple() <em>Expr LSimple</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExprLSimple()
   * @generated
   * @ordered
   */
  protected ExprSimple exprLSimple;

  /**
   * The cached value of the '{@link #getExprRSimple() <em>Expr RSimple</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExprRSimple()
   * @generated
   * @ordered
   */
  protected ExprSimple exprRSimple;

  /**
   * The cached value of the '{@link #getExpr() <em>Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExpr()
   * @generated
   * @ordered
   */
  protected Expr expr;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExprEqImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return WhileDslPackage.Literals.EXPR_EQ;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExprSimple getExprLSimple()
  {
    return exprLSimple;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetExprLSimple(ExprSimple newExprLSimple, NotificationChain msgs)
  {
    ExprSimple oldExprLSimple = exprLSimple;
    exprLSimple = newExprLSimple;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, WhileDslPackage.EXPR_EQ__EXPR_LSIMPLE, oldExprLSimple, newExprLSimple);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setExprLSimple(ExprSimple newExprLSimple)
  {
    if (newExprLSimple != exprLSimple)
    {
      NotificationChain msgs = null;
      if (exprLSimple != null)
        msgs = ((InternalEObject)exprLSimple).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - WhileDslPackage.EXPR_EQ__EXPR_LSIMPLE, null, msgs);
      if (newExprLSimple != null)
        msgs = ((InternalEObject)newExprLSimple).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - WhileDslPackage.EXPR_EQ__EXPR_LSIMPLE, null, msgs);
      msgs = basicSetExprLSimple(newExprLSimple, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WhileDslPackage.EXPR_EQ__EXPR_LSIMPLE, newExprLSimple, newExprLSimple));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExprSimple getExprRSimple()
  {
    return exprRSimple;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetExprRSimple(ExprSimple newExprRSimple, NotificationChain msgs)
  {
    ExprSimple oldExprRSimple = exprRSimple;
    exprRSimple = newExprRSimple;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, WhileDslPackage.EXPR_EQ__EXPR_RSIMPLE, oldExprRSimple, newExprRSimple);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setExprRSimple(ExprSimple newExprRSimple)
  {
    if (newExprRSimple != exprRSimple)
    {
      NotificationChain msgs = null;
      if (exprRSimple != null)
        msgs = ((InternalEObject)exprRSimple).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - WhileDslPackage.EXPR_EQ__EXPR_RSIMPLE, null, msgs);
      if (newExprRSimple != null)
        msgs = ((InternalEObject)newExprRSimple).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - WhileDslPackage.EXPR_EQ__EXPR_RSIMPLE, null, msgs);
      msgs = basicSetExprRSimple(newExprRSimple, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WhileDslPackage.EXPR_EQ__EXPR_RSIMPLE, newExprRSimple, newExprRSimple));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expr getExpr()
  {
    return expr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetExpr(Expr newExpr, NotificationChain msgs)
  {
    Expr oldExpr = expr;
    expr = newExpr;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, WhileDslPackage.EXPR_EQ__EXPR, oldExpr, newExpr);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setExpr(Expr newExpr)
  {
    if (newExpr != expr)
    {
      NotificationChain msgs = null;
      if (expr != null)
        msgs = ((InternalEObject)expr).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - WhileDslPackage.EXPR_EQ__EXPR, null, msgs);
      if (newExpr != null)
        msgs = ((InternalEObject)newExpr).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - WhileDslPackage.EXPR_EQ__EXPR, null, msgs);
      msgs = basicSetExpr(newExpr, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WhileDslPackage.EXPR_EQ__EXPR, newExpr, newExpr));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case WhileDslPackage.EXPR_EQ__EXPR_LSIMPLE:
        return basicSetExprLSimple(null, msgs);
      case WhileDslPackage.EXPR_EQ__EXPR_RSIMPLE:
        return basicSetExprRSimple(null, msgs);
      case WhileDslPackage.EXPR_EQ__EXPR:
        return basicSetExpr(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case WhileDslPackage.EXPR_EQ__EXPR_LSIMPLE:
        return getExprLSimple();
      case WhileDslPackage.EXPR_EQ__EXPR_RSIMPLE:
        return getExprRSimple();
      case WhileDslPackage.EXPR_EQ__EXPR:
        return getExpr();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case WhileDslPackage.EXPR_EQ__EXPR_LSIMPLE:
        setExprLSimple((ExprSimple)newValue);
        return;
      case WhileDslPackage.EXPR_EQ__EXPR_RSIMPLE:
        setExprRSimple((ExprSimple)newValue);
        return;
      case WhileDslPackage.EXPR_EQ__EXPR:
        setExpr((Expr)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case WhileDslPackage.EXPR_EQ__EXPR_LSIMPLE:
        setExprLSimple((ExprSimple)null);
        return;
      case WhileDslPackage.EXPR_EQ__EXPR_RSIMPLE:
        setExprRSimple((ExprSimple)null);
        return;
      case WhileDslPackage.EXPR_EQ__EXPR:
        setExpr((Expr)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case WhileDslPackage.EXPR_EQ__EXPR_LSIMPLE:
        return exprLSimple != null;
      case WhileDslPackage.EXPR_EQ__EXPR_RSIMPLE:
        return exprRSimple != null;
      case WhileDslPackage.EXPR_EQ__EXPR:
        return expr != null;
    }
    return super.eIsSet(featureID);
  }

} //ExprEqImpl
